version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/FlaskOpenRestyConfigurator"
    schedule:
        interval: "weekly"
    target-branch: "dev"
    reviewers:
      - "deNBI/portal-dev"
      - "awalende"
    commit-message:
      prefix: "feat"
      include: "scope"
    open-pull-requests-limit: 15


  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
        interval: "weekly"
    target-branch: "dev"
    reviewers:
      - "deNBI/portal-dev"
      - "awalende"
    commit-message:
      prefix: "feat"
      include: "scope"
    open-pull-requests-limit: 15
    
