---

- name: Update apt cache
  apt:
    cache_valid_time: 1200

- name: Install python3
  apt:
    name: python3
    state: latest

- name: Install pip3
  apt:
    name: python3-pip
    state: latest

- name: Install virtualenv
  apt:
    name: python3-virtualenv
    state: latest