---

- name: Install HAProxy
  apt:
    name: haproxy
    state: latest


- name: Build haproxy ssl key
  shell: "cat /etc/letsencrypt/live/{{ DOMAIN }}/fullchain.pem /etc/letsencrypt/live/{{ DOMAIN }}/privkey.pem | tee /etc/letsencrypt/live/{{ DOMAIN }}/fullchain.pem /etc/letsencrypt/live/{{ DOMAIN }}/{{ DOMAIN }}.pem"
  args:
    creates: "/etc/letsencrypt/live/{{ DOMAIN }}/{{ DOMAIN }}.pem"


- name: Generate HAProxy settings
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Make sure that HAProxy is running
  systemd:
    name: haproxy
    state: restarted