---

- name: Clone forc repo
  git:
    repo: https://github.com/deNBI/simpleVMWebGateway.git
    dest: "{{ FORC_INSTALLATION_PATH }}/simpleVMWebGateway/"
    force: yes
    version: "{{ REPOSITORY_TAG | default(REPOSITORY_BRANCH) | default('dev') }}"


- name: Install requirements in a venv
  pip:
    requirements: "{{ FORC_INSTALLATION_PATH }}simpleVMWebGateway/FastapiOpenRestyConfigurator/requirements.txt"
    virtualenv: "{{ FORC_INSTALLATION_PATH }}simpleVMWebGateway/FastapiOpenRestyConfigurator/venv"
    virtualenv_python: python3

- name: Generate gunicorn config
  template:
    src: gunicorn_conf.py.j2
    dest: "{{ FORC_INSTALLATION_PATH }}simpleVMWebGateway/FastapiOpenRestyConfigurator/gunicorn_conf.py"

- name: Generate systemd unit file for forc
  template:
    src: forc.service.j2
    dest: /etc/systemd/system/forc.service

- name: Generate .env file for forc
  template:
    src: forc.env.j2
    dest: "{{ FORC_INSTALLATION_PATH }}simpleVMWebGateway/FastapiOpenRestyConfigurator/.env"

- name: Copy example templates
  copy:
    src: "{{ FORC_INSTALLATION_PATH }}/simpleVMWebGateway/examples/templates/"
    dest: "{{ FORC_TEMPLATE_PATH }}"
    remote_src: true

- name: Reload systemd daemon and enable forc
  systemd:
    service: forc
    daemon_reload: yes
    enabled: True
    state: restarted
