---

- name: Clone forc repo
  git:
    repo: https://github.com/deNBI/simpleVMWebGateway.git
    dest: "{{ FORC_INSTALLATION_PATH }}/simpleVMWebGateway/"

- name: Install requirements in a venv
  pip:
    requirements: "{{ FORC_INSTALLATION_PATH }}simpleVMWebGateway/FlaskOpenRestyConfigurator/requirements.txt"
    virtualenv: "{{ FORC_INSTALLATION_PATH }}simpleVMWebGateway/FlaskOpenRestyConfigurator/venv"
    virtualenv_python: python3

- name: Generate uwsgi config
  template:
    src: uwsgi.ini.j2
    dest: "{{ FORC_INSTALLATION_PATH }}simpleVMWebGateway/uwsgi.ini"

- name: Generate systemd unit file for forc
  template:
    src: forc.service.j2
    dest: /etc/systemd/system/forc.service

- name: Copy example templates
  copy:
    src: "{{ FORC_INSTALLATION_PATH }}/simpleVMWebGateway/examples/templates/"
    dest: "{{ FORC_TEMPLATE_PATH }}"
    remote_src: true

- name: Reload systemd daemon and enable forc
  systemd:
    service: forc
    daemon_reload: yes
    state: restarted
