---

- name: Install OpenResty pre-required packages
  apt:
    name:
      - wget
      - gnupg
      - ca-certificates
      - software-properties-common
    state: latest

- name: Register OpenResty PGP Key
  apt_key:
    url: https://openresty.org/package/pubkey.gpg
    state: present

- name: Add OpenResty APT repository
  apt_repository:
    repo: "deb http://openresty.org/package/ubuntu {{ ansible_lsb.codename|lower }} main"
    state: present
    update_cache: yes

- name: Install OpenResty
  apt:
    name: openresty
    state: latest

- name: Install lua-resty-openidc, lua-resty-http, lua-resty-session, lua-resty-jwt
  shell: "opm install zmartzone/lua-resty-openidc ledgetech/lua-resty-http bungle/lua-resty-session=3.10 cdbattags/lua-resty-jwt"
  args:
    creates: /usr/local/openresty/site/lualib/resty/openidc.lua

- name: Copy lua function scripts to backend path
  copy:
    src: "{{ FORC_INSTALLATION_PATH }}/simpleVMWebGateway/examples/scripts/"
    dest: "{{ FORC_BACKEND_PATH }}/scripts/"
    remote_src: yes

- name: Generate OpenResty configuration
  template:
    src: nginx.conf.j2
    dest: /etc/openresty/nginx.conf
  register: openresty_config

- name: Copy html files
  copy:
    src: "{{ role_path }}/files/html"
    dest: "/usr/local/openresty/nginx"

- name: Restart OpenResty on config change
  systemd:
    name: openresty
    state: restarted
    enabled: True
  when: openresty_config is changed

- name: Setup log rotation access.log
  cron:
    name: rotate_access_log
    user: root
    minute: "0"
    hour: "0"
    day: "1"
    month: "*"
    weekday: "*"
    job: sudo mv /usr/local/openresty/nginx/logs/access.log /usr/local/openresty/nginx/logs/access.log.0; sudo kill -USR1 `cat /usr/local/openresty/nginx/logs/nginx.pid`

- name: Setup log rotation error.log
  cron:
    name: rotate_error_log
    user: root
    minute: "0"
    hour: "1"
    day: "1"
    month: "*"
    weekday: "*"
    job: sudo mv /usr/local/openresty/nginx/logs/error.log /usr/local/openresty/nginx/logs/error.log.0; sudo kill -USR1 `cat /usr/local/openresty/nginx/logs/nginx.pid`

