---

- name: Install OpenResty pre-required packages
  apt:
    name:
      - wget
      - gnupg
      - ca-certificates
      - software-properties-common
    state: latest

- name: Register OpenResty PGP Key
  apt_key:
    url: https://openresty.org/package/pubkey.gpg
    state: present

- name: Add OpenResty APT repository
  apt_repository:
    repo: deb http://openresty.org/package/ubuntu bionic main
    state: present
    update_cache: yes

- name: Install OpenResty
  apt:
    name: openresty
    state: latest

- name: Install lua-resty-openidc
  shell: "opm install zmartzone/lua-resty-openidc"
  args:
    creates: /usr/local/openresty/site/lualib/resty/openidc.lua

- name: Copy lua function scripts to backend path
  copy:
    src: "{{ FORC_INSTALLATION_PATH }}/simpleVMWebGateway/examples/scripts/"
    dest: "{{ FORC_BACKEND_PATH }}/scripts/"
    remote_src: yes

- name: Generate OpenResty configuration
  template:
    src: nginx.conf.j2
    dest: /etc/openresty/nginx.conf
  register: openresty_config

- name: Restart OpenResty on config change
  systemd:
    name: openresty
    state: restarted
  when: openresty_config is changed
