- name: "Add Docker GPG apt Key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add Docker Repository"
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable"
    state: present

- name: "Update apt and install docker-ce"
  apt: update_cache=yes name=docker-ce state=latest

- name: "Install Docker Module for Python"
  pip:
    name: docker


- name: "Ensure the user {{ ansible_user }} is part of the docker group"
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes


- name: Create forc backup host folder
  file:
    state: directory
    path: "{{ FORC_BACKUP_HOST_PATH }}"
    recurse: yes

- name: Copy Backup files
  copy:
    src: "{{ role_path }}/files"
    dest: "/persistent"

- name: Run the backup-forc container
  shell: |
    docker run -d \
      --name backup-forc \
      --restart always \
      -v "{{ FORC_BACKEND_PATH }}:/backends" \
      -v "{{ FORC_TEMPLATE_PATH }}:/templates" \
      -v "/persistent/files/install-packages.sh:/install-packages.sh" \
      -v "/persistent/files/backup.sh:/etc/cronscripts/backup.sh" \
      -v "/persistent/files/backup-cron:/etc/crontabs/dockercron/backup-cron" \
      -v "{{ FORC_BACKUP_HOST_PATH }}:/etc/backup" \
      -e BACKUP_ROTATION_ENABLED={{ FORC_BACKUP_ROTATION_ENABLED }} \
      -e BACKUP_ROTATION_MAX_SIZE={{ FORC_BACKUP_ROTATION_MAX_SIZE }} \
      -e BACKUP_ROTATION_CUT_SIZE={{ FORC_BACKUP_ROTATION_CUT_SIZE }} \
      -e BACKUP_ROTATION_SIZE_TYP={{ FORC_BACKUP_ROTATION_SIZE_TYP }} \
      quay.io/denbicloud/cron-backup:0.13.5
  args:
    executable: /bin/bash





