---
# tasks file for forc_api

- name: Preparation tasks
  import_tasks: "000-preparation.yml"
  tags:
    - forc_preparation

- name: Package installation tasks
  import_tasks: "005-packages.yml"
  tags:
    - forc_packages

- name: Configuration tasks
  import_tasks: "010-config.yml"
  tags:
    - forc_config

- name: FORC tasks
  import_tasks: "015-forc.yml"
  tags:
    - forc_forc

- name: OpenResty installation tasks
  import_tasks: "020-openresty.yml"
  when: INSTALL_OPENRESTY
  tags:
    - forc_openresty

- name: Backup tasks
  import_tasks: "025-backup.yml"
  when: FORC_BACKUP_ENABLED
  tags:
    - forc_backup
