---
# tasks file for forc_api

- include: "000-preparation.yml"
  tags: ['forc_preparation']

- include: "005-packages.yml"
  tags: ['forc_packages']

- include: "015-forc.yml"
  tags: ['forc_forc']

- include: "020-openresty.yml"
  tags: ['forc_openresty']
  when: INSTALL_OPENRESTY == 'yes'

- include: "025-backup.yml"
  tags: ["forc-backup"]
  when: FORC_BACKUP_ENABLED == 'yes'

