services:
  forc:
    image: forc
    env_file:
      - ../FastapiOpenRestyConfigurator/.env
    volumes:
      - /var/forc/backend_path/:/var/forc/backend_path/:rw
      - /var/forc/template_path/:/var/forc/template_path/:rw
    ports:
      - 0.0.0.0:5000:5000
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443