version: 1
update_configs:
  - package_manager: "python"
    directory: "/FlaskOpenRestyConfigurator"
    update_schedule: "weekly"
    target_branch: "master"
    default_reviewers:
      - "dweinholz"
      - "eKatchko"
      - "vktrrdk"
      - "awalende"
  - package_manager: "docker"
    directory: "/docker"
    update_schedule: "weekly"
    target_branch: "master"
    default_reviewers:
      - "dweinholz"
      - "eKatchko"
      - "vktrrdk"
      - "awalende"

