name: pip-audit

on:
  pull_request:
    types: [opened, reopened, synchronize, edited, review_requested, ready_for_review]
  workflow_dispatch:

jobs:
  pip-audit:
    runs-on: self-hosted
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python 3.14
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: 3.14

      - uses: pypa/gh-action-pip-audit@1220774d901786e6f652ae159f7b6bc8fea6d266 # v1.1.0
        with:
          inputs: FastapiOpenRestyConfigurator/requirements.txt
