galaxy_info:
  author: Alex Walender
  description: This installs OpenResty and FORC on a baremetal Ubuntu 18 or 20 system.
  company: de.NBI
  license: Apache
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal

  galaxy_tags:
    - reverseproxy
    - openresty
    - denbi

dependencies:
    - geerlingguy.certbot
